
#If statement, else statement, else-if statement, nest and chain 

# ---- -2 ---- -1 ---- 0 ---- 1 ---- 2 ----

#We are going to generate a random number from a normally distributed set of numbers

#let's say we are generating a random number that is somewhere close to zero.

#rnorm() function generates a set of numbers that are randomly distributed according to the normal distribution
#rnorm(you can specify three parameters)
rnorm(1)  #1 means you want to generate exactly one number. 

#rnorm(n, mean, sd), by default mean =0 and sd =1.

rnorm(1) #you are assuming mean=0 and sd=1.
rnorm(10) #this will generate 10 random numbers

#let's store the value of rnorm inside a variable.
x <- rnorm(1)

#numbers generated by rnorm() function has very high chances of falling in ---- -2 ---- -1 ---- 0 ---- 1 ---- 2 ----

#using if statement to iidentify where value of rnorm will fall... means between -2 and 2 or -3 and 3 etc.

#if statement
#if statement has three things.
#if(){}, which is similar to ForLoop and WhileLoop. Only difference is that 'if statement' runs only one time. No loops
#if(logical expression). e.g. x>1 will check if the value fell right of 1. means it was positive and greater than 1
#{body}, if logical expression is true than what code must tell.
x <- rnorm(1)
if(x >1){
  y <- "Greater than 1"
}

#Since the logical expression is TRUE, y variable has been created as you see in your global environment.

#How to remove variables in R. why we do that... if value of rnorm() is less than 1, then we want y value to be deleted.
# to do that we use rm() function
rm(y) #I am removing previous value of variable y.
x <- rnorm(1)
if(x >1){
  y <- "Greater than 1"
}
y
#Since logical expression is FALSE, you don't have variable y in your global environment

#else statement
#what if we want something else to happen if logical expression of 'if statement' is FALSE.
#SYNTAX - if(){}else{}
rm(y) #I am removing previous value of variable y.
x <- rnorm(1)
if(x >1){
  y <- "Greater than 1"
}else{
  y <- "less or equal to 1" #if 'if statement is FALSE, then have value of y as less than 1
}

#nested if-elsestatement
#what if you want to check three possiblities. 
#value of x < 0, x == 0, x >0 or something similar.
#SYNTAX- if(){}else{if(){}}
#within the body of else statement, you add another if statement
rm(y) #I am removing previous value of variable y.
x <- rnorm(1)
if(x >=1){
  y <- "Greater than or equal to 1"
}else{
      if(x > -1){
        y <- "between -1 and 1"
      }else{
        y <- "equal to or less than -1"
      }
}


#you can nest another if statement if in else statement in the end. 
#So it can become cumbersome .
#So nested if-else statement is not the best practice.
#What is good than nested??

# else-if statement
#SYANTAX- if(){}else if(){}else{}
rm(y) #I am removing previous value of variable y.
x <- rnorm(1)
if(x >=1){
  y <- "Greater than or equal to 1"
}else if(x > -1){
    y <- "between -1 and 1"
  }else{
    y <- "equal to or less than -1"
  }
#What are we doing here?
#firstly, we check if statement. If not true, we check if else statement. If even that is not true, we go for else.
#code is similar to nested if, but it is much neater.

#else-if statement is called chaining. 
#So nesting and chaining are two diffrent things.


#moving code to the right
#highlight the code you want to move and press TAB key.

#moving code to the left
#highlight the code you want to move and press Shift + TAB key.

#examples
#Check if the number x is divisible by 21. To do that use x %% 21 == 0)
#this means dividing x by 21 leaves a remainder of 0.
rm(x)
rm(y)
x <- 41
if(x %% 21 == 0){
  y <- "divisible by 21"
}else{
  y <- "not divisible by 21"
}

#example
rm(x)
rm(y)
x <- 100
if(x %% 7 == 0 && x %% 9 == 0){
  y <- "x is divisible by both 7 and 9"
}else if(x %% 7 == 0 && x %% 9 != 0 ){
  y <- "x is divisible by 7 but not divisible by 9"
}else{
  if(x %% 7 != 0 && x %% 9 == 0){
    y <- "x is not divisible by 7 but is divisible by 9" 
  }else{
    y <- "x is neither divisible by 7 nor by 9"
  }
}








